In [2]:
import numpy as np

In [3]:
#Element-wise Operations
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

a + b    # [5 7 9]
a - b    # [-3 -3 -3]
a * b    # [4 10 18]
a / b    # [0.25 0.4 0.5]

array([0.25, 0.4 , 0.5 ])

In [5]:
#Scalar Operations (Broadcasting)
a + 10   # [11 12 13]
a * 2    # [2 4 6]

array([2, 4, 6])

In [6]:
#NumPy Math Functions
np.sum(a)     # 6
np.mean(a)    # 2.0
np.max(a)     # 3
np.min(a)     # 1
np.sqrt(a)    # [1. , 1.41, 1.73]
np.exp(a)     # e^x



array([ 2.71828183,  7.3890561 , 20.08553692])

In [7]:
#Operations on 2D Arrays
arr = np.array([[1, 2], [3, 4]])

arr.sum()        # 10
arr.sum(axis=0)  # Column-wise → [4 6]
arr.sum(axis=1)  # Row-wise → [3 7]

array([3, 7])