In [5]:
#Creating NumPy Arrays (1D & 2D) 

In [6]:
import numpy as np
#1D NumPy Array
arr = np.array([10, 20, 30, 40, 50])

print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [7]:
#2D NumPy Array
arr2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr2d)
print("Shape:", arr2d.shape)
print("Dimensions:", arr2d.ndim)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
