In [ ]:
import numpy as np

In [1]:
#Reshaping Arrays
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
print(arr.shape)

(6,)


In [ ]:
#Convert 1D → 2D
reshaped = arr.reshape(2, 3)
print(reshaped)


Output:

[[1 2 3]
 [4 5 6]]


⚠ Rule:
Total elements must match.
2 × 3 = 6 ✔

You can also use -1:

arr.reshape(3, -1)


NumPy automatically calculates the remaining dimension.

🔹 flatten()

Converts multi-dimensional array into 1D copy.

arr2 = np.array([[1,2,3],[4,5,6]])
flat = arr2.flatten()
print(flat)


Output:

[1 2 3 4 5 6]


✔ Returns a copy (changes won’t affect original)

🔹 ravel()

Also converts to 1D.

r = arr2.ravel()
print(r)


✔ Returns a view (not copy)

If you modify r, original may change.